version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - mysql
      - mongodb
      - ollama
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=bd_veille
      - MONGO_URI=mongodb://mongodb:27017/mydb
      - OLLAMA_HOST=http://ollama:11434

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bd_veille
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"

  tests:
    build: 
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - mysql
      - mongodb
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=bd_veille
      - MONGO_URI=mongodb://mongodb:27017/mydb
